name = "awesome fabric client"
author = "Wrham"
version = "2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838843597365424a0e14899502a6faab1e1e02652539c7fc091d148ae0e32991"

[versions]
fabric = "0.12.8"
minecraft = "1.18"

[options]
acceptable-game-versions = ""
