name = "awesome fabric client"
author = "Wrham"
version = "2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6054bf62fd7007e0296c8145c7290fec8ff72baa53e5e83a0490ef33b240d8a"

[versions]
fabric = "0.12.11"
minecraft = "1.18"

[options]
acceptable-game-versions = ""
