name = "Awesome Fabric Client"
author = "Wrham"
version = "2.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8036dcf312b3a4c900162658691a656870a484c3d116586d2702bcc902fdce56"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
