name = "Awesome Fabric Client"
author = "Wrham"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca377050c4e89814cc36631023874a5f88c724b0cdf5ddbfa91b165afeb2267c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
