name = "awesome fabric client"
author = "Wrham"
version = "1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7286050f0e0b5f2593073dc5094e80d6b52c619db6e126cd17f81fa8aede7361"

[versions]
fabric = "0.12.8"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
