name = "awesome fabric client"
author = "Wrham"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8e8f624ac716a78587376362de7076b41294d985d941d274d75b2d15c6ca55e"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
