name = "Animatica"
filename = "animatica-0.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/564/animatica-0.1+1.17.jar"
hash-format = "murmur2"
hash = "624985466"

[update]
[update.curseforge]
file-id = 3478564
project-id = 533006
