name = "Better Game Menu [Forge/Fabric]"
filename = "BetterGameMenu-1.17.1-Fabric-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/971/BetterGameMenu-1.17.1-Fabric-1.2.jar"
hash-format = "murmur2"
hash = "1290117278"

[update]
[update.curseforge]
file-id = 3421971
project-id = 503115
