name = "Fabric Capes"
filename = "Capes-1.2.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3510/854/Capes-1.2.2+1.17.jar"
hash-format = "murmur2"
hash = "3793937648"

[update]
[update.curseforge]
file-id = 3510854
project-id = 408481
