name = "Clear Despawn (Fabric)"
filename = "cleardespawn-1.17.1-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3464/646/cleardespawn-1.17.1-1.1.2.jar"
hash-format = "murmur2"
hash = "2638088035"

[update]
[update.curseforge]
file-id = 3464646
project-id = 308793
