name = "Enhanced Attack Indicator"
filename = "enhanced_attack_indicator-1.0.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/548/enhanced_attack_indicator-1.0.2+1.17.jar"
hash-format = "murmur2"
hash = "2916357959"

[update]
[update.curseforge]
file-id = 3343548
project-id = 446173
