name = "Hat List"
filename = "hatlist-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/520/hatlist-1.2.jar"
hash-format = "murmur2"
hash = "2677755059"

[update]
[update.curseforge]
file-id = 3345520
project-id = 438643
