name = "heads down display"
filename = "heads-down-display-0.1.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/f02hMbGH/versions/0.1.1/heads-down-display-0.1.1.jar"
hash-format = "sha512"
hash = "d4e0faca1e96f83f8681015e1692b26c34fc8d1f2584eb5ede1dceb59ff095f60407ac543c199ff64f4d595b71e77d10fab18ee257a0ea3a0151e31d54cd8d0c"

[update]
[update.modrinth]
mod-id = "f02hMbGH"
version = "Mu0AoFUj"
