name = "Inspecio"
filename = "inspecio-1.1.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/784/inspecio-1.1.0+1.17.jar"
hash-format = "murmur2"
hash = "43055167"

[update]
[update.curseforge]
file-id = 3412784
project-id = 492180
