name = "Inventory Control Tweaks"
filename = "inventory-control-tweaks-1.3.9+MC1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/268/inventory-control-tweaks-1.3.9+MC1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "2066652617"

[update]
[update.curseforge]
file-id = 3519268
project-id = 421375
