name = "Language Reload"
filename = "language-reload-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3510/259/language-reload-1.2.jar"
hash-format = "murmur2"
hash = "2993088515"

[update]
[update.curseforge]
file-id = 3510259
project-id = 527334
