name = "LittleTweaks"
filename = "littletweaks-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/804/littletweaks-1.0.0.jar"
hash-format = "murmur2"
hash = "3895033168"

[update]
[update.curseforge]
file-id = 3519804
project-id = 527975
