name = "Nicephore (better screenshots) [Fabric]"
filename = "nicephore-fabric-1.17.x-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3511/819/nicephore-fabric-1.17.x-1.2.0.jar"
hash-format = "murmur2"
hash = "2055666913"

[update]
[update.curseforge]
file-id = 3511819
project-id = 405990
