name = "No Strip"
filename = "nostrip-1.2.1-1.17+.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/524/nostrip-1.2.1-1.17+.jar"
hash-format = "murmur2"
hash = "1167472011"

[update]
[update.curseforge]
file-id = 3343524
project-id = 405513
