name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.0.0+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3522/785/notenoughcrashes-4.0.0+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "593560028"

[update]
[update.curseforge]
file-id = 3522785
project-id = 353890
