name = "Rebind Narrator"
filename = "rebind-narrator-1.17-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/547/rebind-narrator-1.17-1.0.0.jar"
hash-format = "murmur2"
hash = "2475308895"

[update]
[update.curseforge]
file-id = 3344547
project-id = 296996
