name = "Title Fixer"
filename = "titlefixer-1.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/365/titlefixer-1.0+1.17.jar"
hash-format = "murmur2"
hash = "2899417562"

[update]
[update.curseforge]
file-id = 3476365
project-id = 528170
